// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vybtxdjobjvxyyvbhyyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5YnR4ZGpvYmp2eHl5dmJoeXl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MTE0MDAsImV4cCI6MjA1NzM4NzQwMH0.e3ZHKzASy8MenZkh6WS2PFGE2Y6z6j5K6E-0qhvkfYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);